var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.arrayFromIterator=function(a){for(var b,d=[];!(b=a.next()).done;)d.push(b.value);return d};
$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};function abs(a){return 0<a?a:-a}function hypo(a,b){return Math.sqrt(a*a+b*b)}var Particle=function(a){this.x=a.x||0;this.y=a.y||0;this.xSpeed=a.xSpeed||0;this.ySpeed=a.ySpeed||0;this.mass=void 0===a.mass?1:a.mass;this.density=a.density||1;this.overrideRadius()};
Particle.prototype.distanceTo=function(a,b){var d=this.x-a;var c=this.y-b;d=[{left:d,top:c},{left:d,top:c-h},{left:d-w,top:c-h},{left:d-w,top:c}];for(c=0;4!==c;c++)d[c].distance=hypo(d[c].left,d[c].top);var e=d[0];for(c=1;4!==c;c++)d[c].distance<e.distance&&(e=d[c]);return e};Particle.prototype.move=function(){this.x+=this.xSpeed;this.y+=this.ySpeed};Particle.prototype.getCopy=function(){return new Particle({x:this.x,y:this.y,xSpeed:this.xSpeed,ySpeed:this.ySpeed,mass:this.mass})};
Particle.prototype.overrideRadius=function(){this.radius=Math.sqrt(this.mass*this.density/Math.PI)};Particle.prototype.join=function(a){this.xSpeed=(this.xSpeed*this.mass+a.xSpeed*a.mass)/(this.mass+a.mass);this.ySpeed=(this.ySpeed*this.mass+a.ySpeed*a.mass)/(this.mass+a.mass);this.mass+=a.mass;this.overrideRadius()};window.onresize=overrideCanvasSize;
var particlesCanvas=$("particlesCanvas"),coverCanvas=$("coverCanvas"),particlesCtx=particlesCanvas.getContext("2d"),coverCtx=coverCanvas.getContext("2d"),w,h,partColor=[0,200,40],partRadius=2,particles=[],bufferParticles=[],PI2=2*Math.PI,G=.25,minVelocity=.25,maxVelocity=1.5,edge=!0,panel=document.createElement("div");panel.style="position:fixed; top:0; left:0; width:175px; border: 2px solid green; color:springGreen; padding:4px; background-color:rgba(20,20,20,0.75);";
var div=document.createElement("div"),span=document.createElement("span");div.innerText="Total kinetic energy ";div.appendChild(span);panel.appendChild(div);window.displayTotalSpeed=function(){for(var a=0,b=0;b!==particles.length;b++)a+=particles[b].mass*Math.pow(particles[b].xSpeed+particles[b].ySpeed,2);span.innerText=~~(a/2)};setInterval(displayTotalSpeed,50);var div$1=document.createElement("div"),span$2=document.createElement("span");div$1.innerText="Bodies ";div$1.appendChild(span$2);panel.appendChild(div$1);
window.displayBodies=function(a){span$2.innerText=a};document.body.appendChild(panel);antialiasing(coverCtx,!1);antialiasing(particlesCtx,!1);overrideCanvasSize();init({count:100,minMass:1,maxMass:4,maxVelocity:1.5,minVelocity:.25});displayBodies(particles.length);listener();
function init(a){a=void 0===a?{}:a;void 0===a.count&&(a.count=50);void 0===a.minVelocity&&(a.minVelocity=0);void 0===a.maxVelocity&&(a.maxVelocity=0);void 0===a.minMass&&(a.minMass=1);void 0===a.maxMass&&(a.maxMass=1);particlesCtx.clearRect(0,0,w,h);coverCtx.clearRect(0,0,w,h);for(var b=0,d;b<a.count;b++){d=randFloat(a.minVelocity,a.maxVelocity);var c=(.5<Math.random()?-1:1)*randFloat(0,d);d=[c,(.5<Math.random()?-1:1)*(d-c)];particles.push(new Particle({x:rand(0,w-1),y:rand(0,h-1),xSpeed:d[0],ySpeed:d[1],
mass:rand(a.minMass,a.maxMass)}))}console.log.apply(console,$jscomp.arrayFromIterable(particles));window.test=particles[10].getCopy()}function drawParticles(){particlesCtx.fillStyle=particlesCtx.strokeStyle="rgb("+partColor+")";for(var a=0;a!==particles.length;a++)particlesCtx.beginPath(),particlesCtx.moveTo(~~particles[a].x,~~particles[a].y),particlesCtx.arc(~~particles[a].x,~~particles[a].y,particles[a].radius,0,PI2),particlesCtx.fill(),particlesCtx.stroke()}
function calculate(){for(var a,b,d,c,e=[],g=0,f;g!==particles.length;g++)if(a=particles[g],!e.includes(g))for(f=g+1;f!==particles.length;f++)e.includes(f)||(b=particles[f],d=Math.pow(b.x-a.x,2)+Math.pow(b.y-a.y,2),c=Math.sqrt(d),c<=a.radius+b.radius?(particles[g].join(particles[f]),e.push(f),displayBodies(particles.length-e.length)):(c=G*a.mass*b.mass/d,d=(b.x-a.x)*c,c*=b.y-a.y,particles[g].xSpeed+=d/a.mass,particles[f].xSpeed-=d/b.mass,particles[g].ySpeed+=c/a.mass,particles[f].ySpeed-=c/b.mass));
for(a=0;a!==e.length;a++)particles.splice(e[a]-a,1)}
function drawSpeed(a,b){b=void 0===b?10:b;coverCtx.strokeStyle=void 0===a?"red":a;for(var d=[],c=0;c!==particles.length;c++)d.includes(particles[c].radius)||d.push(particles[c].radius);d=$jscomp.makeIterator(d);for(c=d.next();!c.done;c=d.next()){c=c.value;coverCtx.beginPath();coverCtx.lineWidth=c/2;for(var e=0;e!==particles.length;e++)particles[e].radius===c&&(coverCtx.moveTo(~~particles[e].x,~~particles[e].y),coverCtx.lineTo(~~(particles[e].x+particles[e].xSpeed*b),~~(particles[e].y+particles[e].ySpeed*
b)));coverCtx.stroke()}}function overrideCanvasSize(){particlesCanvas.width=coverCanvas.width=w=window.innerWidth;particlesCanvas.height=coverCanvas.height=h=window.innerHeight}function move(){var a=0;for(len=particles.length;a!==len;a++)particles[a].move()}function copyParticles(){for(var a=0;a!==particles.length;a++)particles[a].getCopy()}
function listener(){move();calculate();particlesCtx.clearRect(0,0,w,h);coverCtx.clearRect(0,0,w,h);drawParticles();drawSpeed();window.requestAnimationFrame(listener)}function stop(){listener=function(){}}function rand(a,b){return Math.round(a-.5+Math.random()*(b-a+1))}function randFloat(a,b){return a+Math.random()*(b-a)}function $(a){return document.getElementById(a)}
function antialiasing(a,b){a.mozImageSmoothingEnabled=a.webkitImageSmoothingEnabled=a.msImageSmoothingEnabled=a.imageSmoothingEnabled=b};