var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
var Particle=function(a){this.x=a.x||0;this.y=a.y||0;this.xSpeed=a.xSpeed||0;this.ySpeed=a.ySpeed||0;this.mass=void 0===a.mass?1:a.mass;this.density=a.density||1;this.overrideRadius()};Particle.prototype.move=function(){this.x+=this.xSpeed;this.y+=this.ySpeed};Particle.prototype.moveFactor=function(a){this.x+=this.xSpeed*a;this.y+=this.ySpeed*a};Particle.prototype.getCopy=function(){return new Particle({x:this.x,y:this.y,xSpeed:this.xSpeed,ySpeed:this.ySpeed,mass:this.mass,density:this.density})};
Particle.prototype.overrideRadius=function(){this.radius=Math.sqrt(this.mass*this.density/Math.PI)};Particle.prototype.join=function(a){var b=this.mass+a.mass;this.xSpeed=(this.xSpeed*this.mass+a.xSpeed*a.mass)/b;this.ySpeed=(this.ySpeed*this.mass+a.ySpeed*a.mass)/b;this.density=Math.round((Math.pow(this.radius,2)*Math.PI+Math.pow(a.radius,2)*Math.PI)/b*1E3)/1E3;this.mass=b;this.mass<a.mass&&(b=this.mass/a.mass,this.x+=(this.x-a.x)*b,this.y+=(this.y-a.y)*b);this.overrideRadius()};
window.onresize=overrideCanvasSize;
var w,h,particles=[],PI2=2*Math.PI,mouse={x:null,y:null,xWorld:null,yWorld:null,distance:null,mousedown:!1,mousemoved:!1},wheel=function(a){a=a||window.event;if(a.wheelDelta){var b=a.wheelDelta;window.opera&&(b=-b)}else a.detail&&(b=-a.detail);0<b?userDisplay.zoom*=1.5:0>b&&(userDisplay.zoom/=1.5);userDisplay.needUpdate=!0;userDisplay.overrideCoords()},mousemoveListener=function(a){mouse.mousemoved=!0;userDisplay.follow(null);userDisplay.needUpdate=!0;mouse.distance+=abs(mouse.x-a.clientX)+abs(mouse.y-
a.clientY);userDisplay.x+=(mouse.x-a.clientX)/userDisplay.zoom;userDisplay.y+=(mouse.y-a.clientY)/userDisplay.zoom;userDisplay.overrideCoords();mouse.x=a.clientX;mouse.y=a.clientY},removeListeners=function(){mouse.mousedown=!1;mouse.mousemoved=!1;mouse.distance=null;particlesCanvas.removeEventListener("mousemove",mousemoveListener);document.body.style.cursor="default"};
particlesCanvas.onmousedown=function(a){mouse.distance=null;mouse.mousedown=!0;mouse.x=a.clientX;mouse.y=a.clientY;particlesCanvas.addEventListener("mousemove",mousemoveListener);document.body.style.cursor="move"};window.onblur=removeListeners;
particlesCanvas.onmouseup=function(a){if(mouse.mousedown&&4>=mouse.distance){var b;a=$jscomp.makeIterator(particles);for(b=a.next();!b.done;b=a.next()){var c=b.value;b=Math.pow(mouse.xWorld-c.x,2)+Math.pow(mouse.yWorld-c.y,2);if(b<=Math.pow(c.radius+userOptions.selectBodyRadius/userDisplay.zoom,2)){userDisplay.bodyToFollow=c;userDisplay.needUpdate=!0;break}}}removeListeners()};
window.addEventListener?window.addEventListener("mousewheel",wheel,!1):window.attachEvent&&window.attachEvent("onmousewheel",wheel);Number.prototype.between=function(a,b){return this>=a&&this<=b};var keys=[];
window.onkeydown=function(a){a=a.keyCode;!keys.includes(a)&&keys.push(a);switch(a){case 32:userOptions.work?world.stop():world.start();break;case 70:userDisplay.followBigger();break;case 82:world.reset();break;case 219:userOptions.simulationSpeed/=2;display.simulationSpeed(userOptions.simulationSpeed);break;case 221:userOptions.simulationSpeed*=2;display.simulationSpeed(userOptions.simulationSpeed);break;default:console.log(a)}};
window.onkeyup=function(a){a=keys.indexOf(a.keyCode);-1!==a&&keys.splice(a,1)};
var display=new function(){var a=this,b=document.createElement("div");b.style="display:none; width:50px; height:50px; border:4px solid rgb(70,70,70); border-radius:50px; color:white; position:fixed; top:15%; left:50%; margin-right:-50%; transform:translate(-50%,0%); background-color:rgba(150,30,30,0.75); cursor:pointer;";b.innerHTML="<span style='position:absolute; top:47%; left:50%; margin-right:-50%; transform:translate(-50%,-50%); font: bold 150% sans-serif;'>| |</span>";this.pause=function(a){return b.style.display=
a?"block":"none"};b.onclick=function(){return world.start()};document.body.appendChild(b);var c=document.createElement("div");c.setAttribute("class","display");c.style="position:fixed; top:0; left:50%; margin-right:-50%; transform:translate(-50%,0%); text-align:center; font-size:110%;";c.innerHTML="<span style='cursor:pointer; padding-right:5px; padding-left:5px;'><</span><span >Simulation speed : </span><span style='position:relative; width:10px;'>1</span><span style='cursor:pointer; padding-right:5px; padding-left:5px;'>></span>";
var d=c.getElementsByTagName("span");this.simulationSpeed=function(a){return d[2].innerText=a};d[0].onclick=function(){return a.simulationSpeed(userOptions.simulationSpeed/=2)};d[3].onclick=function(){return a.simulationSpeed(userOptions.simulationSpeed*=2)};document.body.appendChild(c);c=document.createElement("div");var f=document.createElement("span");c.setAttribute("class","display");c.style="position:fixed; top:0; left:0;";c.innerText="Bodies ";c.appendChild(f);var l;this.bodies=function(a){l!==
a&&(f.innerText=l=a)};document.body.appendChild(c);var g=document.createElement("div");g.setAttribute("class","display");g.style="position:fixed; bottom:0px; left:0px;";g.innerText="x : 0\ny : 0";window.addEventListener("mousemove",function(a){return g.innerText="x : "+(mouse.xWorld=~~(userDisplay.xStart+a.clientX/userDisplay.zoom))+"\ny : "+(mouse.yWorld=~~(userDisplay.yStart+a.clientY/userDisplay.zoom))});document.body.appendChild(g);c=document.createElement("div");c.setAttribute("class","display");
c.style="position:fixed; top:0px; right:0px; font-size:130%; vargin:; width:25px; height:25; text-align:center; cursor:pointer;";c.innerText="H";document.body.appendChild(c);var e=document.createElement("div");e.setAttribute("class","display");e.style="position:fixed; display:none; top: 50%;left: 50%;margin-right: -50%; transform:translate(-50%, -50%)";e.innerHTML="HELP<table><tr><td>Space</td><td>-</td><td>start/stop</td></tr><tr><td>{/}</td><td>-</td><td>slower/faster</td></tr><tr><td>R</td><td>-</td><td>reset</td></tr><tr><td>Mouse</td><td>-</td><td>movement</td></tr><tr><td>Click</td><td>-</td><td>select body to follow</td></tr><tr><td>F</td><td>-</td><td>follow the most bigger body</td></tr></table>";
c.onclick=function(){return e.style.display="none"===e.style.display?"block":"none"};document.body.appendChild(e);this.body={};var k=document.createElement("div");k.setAttribute("class","display");k.style="position:fixed; display:none; top:50%; transform:translate(0%, -50%); margin:0px; width:140px;";k.innerHTML="BODY INFO<br><table><tr><td>Mass</td><td>:</td><td id='bodyMass'>null</td></tr><tr><td>Density</td><td>:</td><td id='bodyDensity'>null</td></tr><tr><td>Radius</td><td>:</td><td id='bodyRadius'>null</td></tr><tr><td>X</td><td>:</td><td id='bodyX'>null</td></tr><tr><td>Y</td><td>:</td><td id='bodyY'>null</td></tr><tr><td>Speed</td><td>:</td><td id='bodySpeed'>null</td></tr></table>";
document.body.appendChild(k);var v=$("bodyMass"),x=$("bodyDensity"),y=$("bodyRadius"),z=$("bodyX"),A=$("bodyY"),B=$("bodySpeed"),m=!1,n,p,q,r,t,u;this.body.show=function(a){a!==m&&(m=a,k.style.display=a?"block":"none")};this.body.mass=function(a){a!==n&&(v.innerText=n=a)};this.body.density=function(a){a!==p&&(x.innerText=p=a)};this.body.radius=function(a){a!==q&&(y.innerText=q=a)};this.body.x=function(a){a!==r&&(z.innerText=r=a)};this.body.y=function(a){a!==t&&(A.innerText=t=a)};this.body.speed=function(a){a!==
u&&(B.innerText=u=a)}},world={G:5,initOptions:{count:750,area:{xStart:0,yStart:0,radius:2500},minMass:1,maxMass:5,maxVelocity:1.5,minVelocity:.5},start:function(){userOptions.work=!0;display.pause(!1)},stop:function(){userOptions.work=!1;display.pause(!0)},reset:function(){particles=[];this.init(this.initOptions);userDisplay.needUpdate=!0;userDisplay.follow(null);userDisplay.x=0;userDisplay.y=0;userDisplay.overrideCoords();userDisplay.update()},init:function(a){a=void 0===a?{}:a;void 0===a.count&&
(a.count=50);void 0===a.minVelocity&&(a.minVelocity=0);void 0===a.maxVelocity&&(a.maxVelocity=0);void 0===a.minMass&&(a.minMass=1);void 0===a.maxMass&&(a.maxMass=1);void 0===a.minDensity&&(a.minDensity=1);void 0===a.maxDensity&&(a.maxDensity=1);userDisplay.clear();for(var b=0,c;b!==a.count;b++){c=randFloat(a.minVelocity,a.maxVelocity);var d=(.5<Math.random()?-1:1)*randFloat(0,c);c=[d,(.5<Math.random()?-1:1)*(c-d)];d=randFloat(0,a.area.radius);var f=randFloat(0,PI2);particles.push(new Particle({x:d*
Math.cos(f),y:d*Math.sin(f),xSpeed:c[0],ySpeed:c[1],mass:rand(a.minMass,a.maxMass),density:randFloat(a.minDensity,a.maxDensity)}))}},removeAlones:function(a){for(var b,c,d=0;d!==particles.length;d++)if(b=Infinity,!(particles[d].mass>world.initOptions.maxMass)){for(var f=0;f!==particles.length;f++)d!==f&&(c=Math.pow(particles[d].x-particles[f].x,2)+Math.pow(particles[d].y-particles[f].y,2),c<b&&(b=c));Math.sqrt(b)>a&&(particles.splice(d,1),d--)}},moveParticles:function(){for(var a=0;a!==particles.length;a++)particles[a].move()},
moveParticlesFactor:function(a){for(var b=0;b!==particles.length;b++)particles[b].moveFactor(a)},calculate:function(){for(var a,b,c,d,f,l=!1,g=0,e;g!==particles.length;g++){a=particles[g];for(e=g+1;e!==particles.length;e++)b=particles[e],d=b.x-a.x,f=b.y-a.y,c=d*d+f*f,c<=Math.pow(a.radius+b.radius,2)?(particles[g].join(particles[e]),userDisplay.bodyToFollow===b&&(userDisplay.bodyToFollow=a),particles.splice(e,1),e--,g<=e&&(l=!0)):(c=world.G/c/(abs(d)+abs(f)),d*=c,f*=c,particles[g].xSpeed+=d*b.mass,
particles[e].xSpeed-=d*a.mass,particles[g].ySpeed+=f*b.mass,particles[e].ySpeed-=f*a.mass);l&&(g--,l=!1)}display.bodies(particles.length)},calculateFactor:function(a){for(var b,c,d,f,l,g=!1,e=0,k;e!==particles.length;e++){b=particles[e];for(k=e+1;k!==particles.length;k++)c=particles[k],f=c.x-b.x,l=c.y-b.y,d=Math.pow(f,2)+Math.pow(l,2),d<=Math.pow(b.radius+c.radius,2)?(particles[e].join(particles[k]),userDisplay.bodyToFollow===c&&(userDisplay.bodyToFollow=b),particles.splice(k,1),k--,e<=k&&(g=!0)):
(d=world.G/d/(abs(f)+abs(l))*a,f*=d,l*=d,particles[e].xSpeed+=f*c.mass,particles[k].xSpeed-=f*b.mass,particles[e].ySpeed+=l*c.mass,particles[k].ySpeed-=l*b.mass);g&&(e--,g=!1)}display.bodies(particles.length)}},userDisplay={underCanvas:$("underCanvas"),particlesCanvas:$("particlesCanvas"),underCtx:this.underCanvas.getContext("2d",{alpha:!1}),particlesCtx:this.particlesCanvas.getContext("2d",{alpha:!0}),xStart:null,yStart:null,xEnd:null,yEnd:null,x:0,y:0,buff:{PI2:2*Math.PI,particlesInRange:[],radiuses:[]},
followBigger:function(){if(0!==particles.length){for(var a=particles[0],b=0;b!==particles.length;b++)particles[b].mass>a.mass&&(a=particles[b]);this.bodyToFollow=a;this.follow(a)}},up:function(a){a=void 0===a?userOptions.movingSpeed:a;this.y-=a/this.zoom;this.needUpdate=!0;this.overrideCoords()},down:function(a){a=void 0===a?userOptions.movingSpeed:a;this.y+=a/this.zoom;this.needUpdate=!0;this.overrideCoords()},left:function(a){a=void 0===a?userOptions.movingSpeed:a;this.x-=a/this.zoom;this.needUpdate=
!0;this.overrideCoords()},right:function(a){a=void 0===a?userOptions.movingSpeed:a;this.x+=a/this.zoom;this.needUpdate=!0;this.overrideCoords()},needUpdate:!1,update:function(){this.needUpdate&&(this.bodyToFollow&&this.follow(),this.overrideRange(),this.buff.particlesInRange.length&&(this.clear(),this.drawParticles(),this.drawSpeed()),this.needUpdate=!1)},zoom:1,forceClear:function(){this.underCtx.clearRect(0,0,w,h);this.particlesCtx.clearRect(0,0,w,h)},clear:function(){0!==this.buff.particlesInRange.length&&
(this.underCtx.clearRect(0,0,w,h),this.particlesCtx.clearRect(0,0,w,h))},bodyToFollow:null,follow:function(a){a=void 0===a?this.bodyToFollow:a;if(null===a)this.bodyToFollow=null,display.body.show(!1);else if(display.body.show(!0),this.x!==a.x||this.y!==a.y)display.body.mass(round(a.mass,2)),display.body.density(round(a.density,2)),display.body.radius(round(a.radius,2)),display.body.x(round(a.x,1)),display.body.y(round(a.y,1)),display.body.speed(round(a.xSpeed,1)+" "+round(a.ySpeed,1)),this.needUpdate=
!0,this.x=a.x,this.y=a.y,this.overrideCoords()},drawParticles:function(){for(var a=0;a!==this.buff.particlesInRange.length;a++)this.particlesCtx.fillStyle=this.particlesCtx.strokeStyle="rgb(0,"+~~(140+100/this.buff.particlesInRange[a].density)+",40)",this.particlesCtx.beginPath(),this.particlesCtx.arc((this.buff.particlesInRange[a].x-this.xStart)*this.zoom,(this.buff.particlesInRange[a].y-this.yStart)*this.zoom,floor(this.buff.particlesInRange[a].radius*this.zoom),0,PI2),this.particlesCtx.fill(),
this.particlesCtx.stroke();null!==this.bodyToFollow&&(this.particlesCtx.lineWidth=2,this.particlesCtx.strokeStyle="rgba(0,255,255,0.75)",this.particlesCtx.beginPath(),this.particlesCtx.arc((this.bodyToFollow.x-this.xStart)*this.zoom,(this.bodyToFollow.y-this.yStart)*this.zoom,~~((this.bodyToFollow.radius+5)*this.zoom)+10,0,PI2),this.particlesCtx.stroke())},drawSpeed:function(a,b){b=void 0===b?10:b;this.underCtx.strokeStyle=void 0===a?"red":a;var c;this.buff.radiuses=[];for(c=0;c!==this.buff.particlesInRange.length;c++)this.buff.radiuses.includes(this.buff.particlesInRange[c].radius)||
this.buff.radiuses.push(this.buff.particlesInRange[c].radius);var d=$jscomp.makeIterator(this.buff.radiuses);for(c=d.next();!c.done;c=d.next()){var f=c.value;this.underCtx.beginPath();this.underCtx.lineWidth=f/2*this.zoom;for(c=0;c!==this.buff.particlesInRange.length;c++)this.buff.particlesInRange[c].radius===f&&(this.underCtx.moveTo(~~((this.buff.particlesInRange[c].x-this.xStart)*this.zoom),~~((this.buff.particlesInRange[c].y-this.yStart)*this.zoom)),this.underCtx.lineTo(~~((this.buff.particlesInRange[c].x-
this.xStart+this.buff.particlesInRange[c].xSpeed*b)*this.zoom),~~((this.buff.particlesInRange[c].y-this.yStart+this.buff.particlesInRange[c].ySpeed*b)*this.zoom)));this.underCtx.stroke()}},overrideRange:function(){this.buff.particlesInRange=[];for(i=0;i!==particles.length;i++)particles[i].x.between(this.xStart-particles[i].radius,this.xEnd+particles[i].radius)&&particles[i].y.between(this.yStart-particles[i].radius,this.yEnd+particles[i].radius)&&this.buff.particlesInRange.push(particles[i])},overrideCoords:function(){this.xStart=
this.x-w/2/this.zoom;this.yStart=this.y-h/2/this.zoom;this.xEnd=this.xStart+w/this.zoom;this.yEnd=this.yStart+h/this.zoom}},userOptions={work:!0,movingSpeed:15,selectBodyRadius:20,simulationSpeed:1};antialiasing(userDisplay.underCtx,!1);antialiasing(userDisplay.particlesCtx,!1);overrideCanvasSize();userDisplay.overrideCoords();world.reset();display.bodies(particles.length);listener();setInterval(function(){return world.removeAlones(2E4)},3E3);
function overrideCanvasSize(){userDisplay.particlesCanvas.width=userDisplay.underCanvas.width=w=window.innerWidth;userDisplay.particlesCanvas.height=userDisplay.underCanvas.height=h=window.innerHeight;userDisplay.needUpdate=!0;userDisplay.update()}
function listener(){if(keys.length)for(var a=$jscomp.makeIterator(keys),b=a.next();!b.done;b=a.next())key=b.value,37===key?userDisplay.left():39===key&&userDisplay.right(),38===key?userDisplay.up():40===key&&userDisplay.down();if(userOptions.work){if(1<=userOptions.simulationSpeed)for(a=0;a!==userOptions.simulationSpeed;a++)world.moveParticles(),world.calculate();else world.moveParticlesFactor(userOptions.simulationSpeed),world.calculateFactor(userOptions.simulationSpeed);userDisplay.needUpdate=!0}userDisplay.update();
window.requestAnimationFrame(listener)}function rand(a,b){return Math.round(a-.5+Math.random()*(b-a+1))}function floor(a){return~~a===a?a:a+1}function randFloat(a,b){return a+Math.random()*(b-a)}function $(a){return document.getElementById(a)}function antialiasing(a,b){a.mozImageSmoothingEnabled=a.webkitImageSmoothingEnabled=a.msImageSmoothingEnabled=a.imageSmoothingEnabled=b}function abs(a){return 0<a?a:-a}function round(a,b){b=void 0===b?0:b;return~~(a*Math.pow(10,b))/Math.pow(10,b)}
function pow(a,b){return 2===b?a*a:1===b?a:a*b};