var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,b){a.raw=b;return a};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
setInterval(console.clear,6E4);reloadMe=function(){};var isFramed;try{isFramed=window!=window.top||document!=top.document||self.location!=top.location}catch(a){isFramed=!0}isFramed&&window.open(location.href);Number.prototype.between=function(a,b){return this>a&&this<b};Object.defineProperty(Object.prototype,"forEach",{__proto__:null,value:function(a){var b=Object.keys(this);b=$jscomp.makeIterator(b);for(var c=b.next();!c.done;c=b.next())c=c.value,a.call(null,this[c],c)}});
var antialiasing=function(a,b){a.mozImageSmoothingEnabled=a.webkitImageSmoothingEnabled=a.msImageSmoothingEnabled=a.imageSmoothingEnabled=b},get=function(a){return new Promise(function(b,c){var d=new XMLHttpRequest;d.onload=function(){b(d.responseText);d=null};d.onerror=c;d.open("GET",a);d.send()})},setSizes=function(a){a=void 0===a?pxlSize:a;sensitivityX=canvas.width/2/a;sensitivityY=canvas.height/2/a;x_left=x-canvas.width/2/a;y_top=y-canvas.height/2/a},getZoom=function(){return place.zooming.zoomScale},
getCoords=function(){var a=place.getCanvasCursorPosition();return[a.x,a.y]},resize=function(){canvas.width=window.innerWidth*minimapWidth/100-minimapButton.offsetWidth;canvas.height=window.innerHeight*minimapHeight/100-minimapButton.offsetHeight;antialiasing(ctx,!1);minimapShow&&drawTemplates()},drawCover=function(){2>=pxlSize||(ctx.beginPath(),ctx.lineWidth===pxlSize/3||(ctx.lineWidth=pxlSize/3),ctx.strokeStyle="springGreen",ctx.rect(canvas.width/2,canvas.height/2,pxlSize,pxlSize),ctx.stroke())},
drawTemplates=function(){ctx.clearRect(0,0,canvas.width,canvas.height);templates.forEach(function(a,b){x.between(a.x-sensitivityX,a.xEnd+sensitivityX)&&y.between(a.y-sensitivityY,a.yEnd+sensitivityY)&&(a.loaded?ctx.drawImage(a.image,~~((a.x-x_left)*pxlSize),~~((a.y-y_top)*pxlSize),~~(a.width*pxlSize),~~(a.height*pxlSize)):loadTemplate(b))});drawCover()},loadTemplate=function(a){if(!templates[a].loaded&&!templates[a].loadingStarted){console.log('Loading template "'+a+'"');templates[a].loadingStarted=
!0;var b=new Image;b.crossOrigin="";b.onload=function(){templates[a].image=b;templates[a].loaded=!0;console.log('Template "'+a+'" loaded"')};b.onerror=function(){return delete templates[a]};b.src=faction.images+a+".png"}},hideMinimap=function(){minimapShow=!1;canvas.style.display="none";minimapButton.style.color="white";minimapButton.innerText="Minimap";resize()},showMinimap=function(){minimapShow=!0;canvas.style.display="block";minimapButton.style.color="red";minimapButton.innerText="Off";resize()},
x,y,newX,newY,pxlSize,sensitivityX,sensitivityY,x_left,y_top,minimapWidth=25,minimapHeight=33,minimapShow=!0,faction={name:"MLPP",data:"https://raw.githubusercontent.com/EndlessNightNLR/endlessnightnlr.github.io/master/MLPP/MiniPixel/templates.json",images:"https://raw.githubusercontent.com/EndlessNightNLR/endlessnightnlr.github.io/master/images/"},templates={},minimapBox=document.createElement("div"),minimapButton=document.createElement("span"),canvas=document.createElement("canvas"),ctx=canvas.getContext("2d");
minimapBox.style="position:fixed; top:50%; right:0; transform:translate(0%,-50%); background-color:rgb(0,0,0,0.85); z-index:9999; padding:5px; text-align:center;";minimapButton.style="cursor:pointer; font-weight:bold;";minimapButton.addEventListener("click",function(){return minimapShow?hideMinimap():showMinimap()});minimapBox.appendChild(canvas);minimapBox.appendChild(minimapButton);document.body.appendChild(minimapBox);minimapShow?showMinimap():hideMinimap();
window.addEventListener("mousemove",function(){var a=$jscomp.makeIterator(getCoords());newX=a.next().value;newY=a.next().value;if(newX!==x||newY!==y)x=newX,y=newY,pxlSize=getZoom(),setSizes(),drawTemplates()});window.addEventListener("wheel",function(){return pxlSize=getZoom(),setSizes(),drawTemplates()});
get(faction.data).then(function(a){JSON.parse(a).forEach(function(a,c){templates[c]={name:c,x:a.x,y:a.y,xEnd:a.x+a.width,yEnd:a.y+a.height,width:a.width,height:a.height,loadingStarted:!1,loaded:!1}});console.log("Template list downloaded");console.dir(templates)},console.error);
(function ub(){let n=document.getElementById('preloaderapp2');n?n.parentNode.removeChild(n):setTimeout(ub,100);})();
